-- Getting Current Date and Timestamp
SELECT
    CURRENT_DATE AS CURRENT_DATE;


SELECT
    CURRENT_TIMESTAMP AS CURRENT_TIMESTAMP;


SELECT
    SUBSTRING(CURRENT_DATE::VARCHAR, 1, 4) AS CURRENT_DATE;