/*
Exercise 3 - Revenue Per Customer
Get the revenue generated by each customer for the month of 2014 January

Tables - orders, order_items and customers
Data should be sorted in descending order by revenue and then ascending order by customer_id
Output should contain customer_id, customer_first_name, customer_last_name, customer_revenue.
If there are no orders placed by customer, then the corresponding revenue for a give customer should be 0.
Consider only COMPLETE and CLOSED orders
*/
SELECT
	c.customer_id
  , c.customer_fname
  , c.customer_lname
  , ROUND(SUM(oi.order_item_subtotal::numeric), 2) AS customer_revenue  
FROM
	order_items AS oi
LEFT OUTER JOIN
	orders AS o
ON
	oi.order_item_order_id = o.order_id
INNER JOIN
	customers AS c
ON
	o.order_customer_id = c.customer_id
WHERE
	o.order_status IN ('CLOSED', 'COMPLETE')
GROUP BY
	c.customer_id
  , c.customer_fname
  , c.customer_lname
ORDER BY
	customer_revenue